#!/usr/bin/env python3
"""
Module to interact with the Star Wars API (SWAPI) to find starships
that can hold a given number of passengers.
"""

import requests


def availableShips(passengerCount: int) -> list[str]:
        """
            Retrieves a list of starship names from the Star Wars API (SWAPI)
                that can accommodate a specified number of passengers.

                    The function iterates through all available starships, handling pagination.
                        Ships with unknown or non-numeric passenger capacities are ignored.

                            Args:
                                        passengerCount (int): The minimum number of passengers the ships
                                                                      must be able to carry.

                                                                          Returns:
                                                                                      list[str]: A list of names of starships that meet the passenger
                                                                                                         capacity requirement. Returns an empty list if no
                                                                                                                            ships are found or if there's an issue fetching data.
                                                                                                                                """
                                                                                                                                    url = 'https://swapi-api.alx-tools.com/api/starships/'
                                                                                                                                        output_ship_names = []  # Initialize an empty list to store matching ship names

                                                                                                                                            while url:  # Loop continues as long as there's a 'next' URL to fetch
                                                                                                                                                        try:
                                                                                                                                                                        # Make the HTTP GET request to the current URL
                                                                                                                                                                                    res = requests.get(url)
                                                                                                                                                                                                res.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)

                                                                                                                                                                                                            # Parse the JSON response
                                                                                                                                                                                                                        data = res.json()

                                                                                                                                                                                                                                    # Iterate through the starships in the current page's results
                                                                                                                                                                                                                                                for ship in data.get('results', []):
                                                                                                                                                                                                                                                                    # Get the 'passengers' string and remove commas for conversion
                                                                                                                                                                                                                                                                                    passengers_str = ship.get('passengers', '0').replace(',', '')

                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                            # Convert passenger string to integer
                                                                                                                                                                                                                                                                                                                                                passenger_capacity = int(passengers_str)

                                                                                                                                                                                                                                                                                                                                                                    # Check if the ship's capacity meets the requirement
                                                                                                                                                                                                                                                                                                                                                                                        if passenger_capacity >= passengerCount:
                                                                                                                                                                                                                                                                                                                                                                                                                    output_ship_names.append(ship.get('name'))
                                                                                                                                                                                                                                                                                                                                                                                                                                    except ValueError:
                                                                                                                                                                                                                                                                                                                                                                                                                                                            # If conversion to int fails (e.g., 'n/a', 'unknown'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # simply skip this ship as its capacity is not quantifiable.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pass

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Update the URL to the next page for pagination
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # If 'next' is None, the loop will terminate
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    url = data.get('next')

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except requests.exceptions.RequestException as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Handle any request-related errors (network issues, bad URLs, etc.)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Error fetching data from SWAPI: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break  # Exit the loop on error
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except ValueError as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Handle JSON decoding errors if res.json() fails
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"Error decoding JSON response: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Catch any other unexpected errors
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"An unexpected error occurred: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return output_ship_names

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Example usage (for testing purposes, you can remove this in your final script)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("Testing with passenger count = 4:")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ships_for_4 = availableShips(4)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for ship in ships_for_4:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(ship)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("\nTesting with passenger count = 200000:")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ships_for_200000 = availableShips(200000)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for ship in ships_for_200000:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(ship)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("\nTesting with passenger count = 20000000:")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ships_for_20000000 = availableShips(20000000)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         for ship in ships_for_20000000:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  print(ship)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      print("\nTesting with passenger count = 310:")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ships_for_310 = availableShips(310)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              for ship in ships_for_310:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          print(ship)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              print("\nTesting with passenger count = 0 (should return all ships with known capacity):")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ships_for_0 = availableShips(0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      for ship in ships_for_0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(ship)


